repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: backend/.venv/bin/ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: backend/.venv/bin/ruff format
        language: system
        types: [python]