# Generated by Django 4.2.30 on 2026-06-18 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_credentials", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api_connector_auth_config",
            },
        ),
        migrations.CreateModel(
            name="ConnectionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.CharField(max_length=2048)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("api_key", "API Key"),
                            ("bearer", "Bearer Token"),
                            ("basic", "Basic Auth"),
                            ("oauth_cc", "OAuth Client Credentials"),
                            ("oauth_ac", "OAuth Authorization Code"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("default_headers", models.JSONField(blank=True, default=list)),
                ("ssl_verify", models.BooleanField(default=True)),
                ("request_timeout", models.IntegerField(default=30)),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_outcome", models.BooleanField(blank=True, null=True)),
                ("last_test_status_code", models.IntegerField(blank=True, null=True)),
                ("last_test_response_time", models.IntegerField(blank=True, null=True)),
                (
                    "last_test_detected_format",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api_connector_connection_profile",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=2048)),
                (
                    "method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")],
                        default="GET",
                        max_length=4,
                    ),
                ),
                ("query_params", models.JSONField(blank=True, default=list)),
                ("path_variables", models.JSONField(blank=True, default=dict)),
                ("request_body", models.JSONField(blank=True, null=True)),
                ("endpoint_headers", models.JSONField(blank=True, default=list)),
                (
                    "data_root_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "record_count_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="api_connector.connectionprofile",
                    ),
                ),
            ],
            options={
                "db_table": "api_connector_endpoint",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchemaField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_path", models.CharField(max_length=500)),
                ("alias", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "inferred_type",
                    models.CharField(
                        choices=[
                            ("null", "Null"),
                            ("boolean", "Boolean"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("string", "String"),
                            ("mixed", "Mixed"),
                            ("array_of_objects", "Array of Objects"),
                            ("array_of_primitives", "Array of Primitives"),
                        ],
                        default="string",
                        max_length=30,
                    ),
                ),
                (
                    "type_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("null", "Null"),
                            ("boolean", "Boolean"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("string", "String"),
                            ("mixed", "Mixed"),
                            ("array_of_objects", "Array of Objects"),
                            ("array_of_primitives", "Array of Primitives"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("include", models.BooleanField(default=True)),
                (
                    "array_handling",
                    models.CharField(
                        blank=True,
                        choices=[("expand", "Expand"), ("retain", "Retain")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("null_percentage", models.FloatField(default=0.0)),
                ("sample_value", models.JSONField(blank=True, null=True)),
                ("stale", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_fields",
                        to="api_connector.endpoint",
                    ),
                ),
            ],
            options={
                "db_table": "api_connector_schema_field",
                "ordering": ["key_path"],
            },
        ),
        migrations.CreateModel(
            name="PaginationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("no_pagination", "No Pagination"),
                            ("offset_limit", "Offset/Limit"),
                            ("page_size", "Page/Size"),
                            ("cursor", "Cursor"),
                            ("next_url", "Next URL"),
                            ("link_header", "Link Header"),
                        ],
                        default="no_pagination",
                        max_length=20,
                    ),
                ),
                ("strategy_params", models.JSONField(blank=True, default=dict)),
                ("max_pages", models.IntegerField(default=100)),
                ("max_records", models.IntegerField(default=10000)),
                ("inter_page_delay_ms", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagination_config",
                        to="api_connector.endpoint",
                    ),
                ),
            ],
            options={
                "db_table": "api_connector_pagination_config",
            },
        ),
        migrations.CreateModel(
            name="ConnectionTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tested_at", models.DateTimeField(auto_now_add=True)),
                ("step_results", models.JSONField(default=list)),
                ("overall_passed", models.BooleanField(default=False)),
                ("test_path", models.CharField(blank=True, max_length=2048, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="api_connector.connectionprofile",
                    ),
                ),
            ],
            options={
                "db_table": "api_connector_connection_test_result",
                "ordering": ["-tested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="connectionprofile",
            index=models.Index(fields=["name"], name="api_connect_name_94a37a_idx"),
        ),
        migrations.AddField(
            model_name="authconfig",
            name="connection_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_config",
                to="api_connector.connectionprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="schemafield",
            index=models.Index(
                fields=["endpoint", "include"], name="api_connect_endpoin_a2d76f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schemafield",
            unique_together={("endpoint", "key_path")},
        ),
        migrations.AlterUniqueTogether(
            name="endpoint",
            unique_together={("connection_profile", "name")},
        ),
        migrations.AddIndex(
            model_name="connectiontestresult",
            index=models.Index(
                fields=["connection_profile", "tested_at"],
                name="api_connect_connect_e20ed7_idx",
            ),
        ),
    ]
