# Generated by Django 4.2.30 on 2026-06-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_connector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authconfig",
            name="credentials_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
