# Generated by Django 4.2.30 on 2026-06-22 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_connector", "0002_authconfig_credentials_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("oauth_cc", "OAuth Client Credentials"),
                            ("oauth_ac", "OAuth Authorization Code"),
                        ],
                        default="oauth_cc",
                        max_length=10,
                    ),
                ),
                ("encrypted_token", models.TextField()),
                ("encrypted_refresh_token", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_tokens",
                        to="api_connector.connectionprofile",
                    ),
                ),
            ],
            options={
                "db_table": "api_connector_oauth_token",
                "unique_together": {("connection_profile", "token_type")},
            },
        ),
    ]
