# Generated by Django 4.2.30 on 2026-06-23 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_connector", "0003_oauth_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthACState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255, unique=True)),
                (
                    "pkce_code_verifier",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "pkce_code_challenge",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "redirect_origin",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_states",
                        to="api_connector.connectionprofile",
                    ),
                ),
            ],
            options={
                "db_table": "api_connector_oauth_ac_state",
                "indexes": [
                    models.Index(fields=["state"], name="api_connect_state_d62dac_idx"),
                    models.Index(
                        fields=["connection_profile", "used"],
                        name="api_connect_connect_cc53e1_idx",
                    ),
                ],
            },
        ),
    ]
