# Generated by Django 4.2.30 on 2026-07-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_connector", "0004_oauth_ac_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="response_format",
            field=models.CharField(
                choices=[("json", "JSON"), ("xml", "XML")],
                default="json",
                max_length=10,
            ),
        ),
    ]
